<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simmodel2">
  <eClassifiers xsi:type="ecore:EClass" name="Clazz">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueMin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subs" eType="#//ClazzSub"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClazzSub" eSuperTypes="#//Clazz">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attA"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attB"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsubs" eType="#//ClassSubSub"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassSubSub" eSuperTypes="#//ClazzSub">
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalClasses" eType="#//Final"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Final"/>
</ecore:EPackage>
