<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:mappingLanguage="http://www.big.tuwien.ac.at/mappingLanguage" name="test2tests">
  <eClassifiers xsi:type="mappingLanguage:C2C" name="C2C">
    <leftEnds refClass="#//tests/A"/>
    <rightEnds refClass="#//test/A"/>
  </eClassifiers>
  <eClassifiers xsi:type="mappingLanguage:C2C" name="C2C">
    <leftEnds refClass="#//tests/B"/>
    <rightEnds refClass="#//test/B"/>
  </eClassifiers>
  <eClassifiers xsi:type="mappingLanguage:A2A" name="A2A" context="#//C2C.1">
    <leftEnds refAttribute="#//test/B/b"/>
    <rightEnds refAttribute="#//tests/B/b"/>
  </eClassifiers>
  <eClassifiers xsi:type="mappingLanguage:R2R" containerContext="#//C2C" refContext="#//C2C.1">
    <leftEnds refReference="#//test/A/b"/>
    <rightEnds refReference="#//tests/A/b"/>
  </eClassifiers>
  <eSubpackages name="test" nsURI="http://test" nsPrefix="test">
    <eClassifiers xsi:type="ecore:EClass" name="A">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//test/B"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="tests" nsURI="http://tests" nsPrefix="tests">
    <eClassifiers xsi:type="ecore:EClass" name="A">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="b" eType="#//tests/B"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="B">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
